services:
  joytag-api:
    build: .
    container_name: joytag_api_server
    ports:
      - "8000:8000"
    
    # ★★★ ここがガチの魔改造ポイント！ ★★★
    
    # --workers 1 を追加して、プロセスが1個で動くように指定！
    # これでログの重複問題が解決するはずだよ✨
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]
    
    # コンテナがちゃんと生きてるかチェックする機能を追加
    healthcheck:
      # 30秒ごとに「curl http://localhost:8000」を試して！
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s    # チェックの間隔
      timeout: 10s     # タイムアウトまでの時間
      retries: 3       # 失敗した場合に3回までリトライ
      start_period: 60s # コンテナ起動後、チェック開始まで60秒待つ（モデルロード用）

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped